Added status full loaded into FileData
sfztools/sfizz pull request #1246
Opened 2024-02-14 07:29 UTC by KKQ-KKQ

PR 1/4 of #1236 Shared File Pool

Added FileData::Status::FullLoaded.

2024-02-15 20:01 UTC, paulfd requested changes
2 questions:
- If we move to having a single background thread for loading, this logic and the atomics would get much easier, wouldn't it?
- It seems we're so close to not needing the `loadedFiles`. The only issue I see is if someone calls `setRamLoading(true)`, and then `setRamLoading(false)`, which would erase the `FullyLoaded` states from before.

2024-02-15 20:01 UTC, paulfd commented on src/sfizz/FilePool.h
> +    enum class Status { Invalid, Preloaded, Streaming, Done, FullLoaded };
Let's call this `FullyLoaded`.

2024-02-15 20:01 UTC, paulfd commented on src/sfizz/FilePool.cpp
> +    if (currentStatus == FileData::Status::Streaming) {
Given the `compare_exchange` below, shouldn't this be `while (currentStatus != FileData::Status::Done)`?

2024-02-15 20:01 UTC, paulfd commented on src/sfizz/FilePool.cpp
> +        const uint32_t maxOffset = fileData.information.maxOffset;
Maybe we need to make the `maxOffset` in `information` a `uint32_t`. I don't recall why I put an `int64_t`, maybe for full generality and to better support integer arithmetics since you tend to add or remove offsets around. Was there a reason for you to force `uint32_t` here?

2024-02-15 20:01 UTC, paulfd commented on src/sfizz/FilePool.cpp
> +            fileData.status.compare_exchange_strong(status, FileData::Status::Preloaded);
Same comment as below re: `compare_exchange` without a while loop.

2024-02-15 20:01 UTC, paulfd commented on src/sfizz/FilePool.cpp
> +            // Initially set status
We can remove this comment I think.

2024-02-15 20:01 UTC, paulfd commented on src/sfizz/FilePool.cpp
> +        switch(status) {
Previously you mentioned the switch was needed because `status` was an atomic, but here it's not, right? Would it be okay to make this an `if`? It's just so much clearer to me.

2024-02-15 20:01 UTC, paulfd requested changes
Edit: duplicate comment

2024-02-15 20:02 UTC, paulfd reviewed
And thanks for the PR as always :)

2024-02-16 00:04 UTC, KKQ-KKQ commented on src/sfizz/FilePool.h
> +    enum class Status { Invalid, Preloaded, Streaming, Done, FullLoaded };
It might be better that we have a boolean fullyLoaded variable on FileData instead of adding it's status enum.

2024-02-16 00:10 UTC, KKQ-KKQ commented on src/sfizz/FilePool.cpp
> +    if (currentStatus == FileData::Status::Streaming) {
status should not be changed to Done when the status is changed to FullLoaded.
but it is a little bit dangerous in the following situation:
1. fileData starts streaming
2. status is changed to FullLoaded (e.g. setRamLoading(true))
3. status is changed to Preloaded (e.g. setRamLoading(false))
4. fileData finishes streaming

I will consider more.

2024-02-16 00:11 UTC, KKQ-KKQ commented on src/sfizz/FilePool.cpp
> +        const uint32_t maxOffset = fileData.information.maxOffset;
No. I will fix this.

2024-02-16 00:13 UTC, KKQ-KKQ commented on src/sfizz/FilePool.cpp
> +        switch(status) {
I don't care either way, I will change this if you prefer `if`.

2024-02-16 00:28 UTC, KKQ-KKQ commented
> 2 questions:
> 
> * If we move to having a single background thread for loading, this logic and the atomics would get much easier, wouldn't it?
If we moved to having a single background thread for loading and having shared file pool, an instance have to wait until another instance finishes loading.

> * It seems we're so close to not needing the `loadedFiles`. The only issue I see is if someone calls `setRamLoading(true)`, and then `setRamLoading(false)`, which would erase the `FullyLoaded` states from before.
`loadedFiles` is for smaller files and for wave-oscillators and the samples in it should not be released even when `preloadSize` is changed.
I think we needs the `loadedFiles`.

2024-02-16 00:33 UTC, KKQ-KKQ commented
> 2 questions:
> 
> * If we move to having a single background thread for loading, this logic and the atomics would get much easier, wouldn't it?

Oh do you mean `finalizeSfzLoad()` just queue loading? I think it might be more complex, but worth consider it.

2024-02-16 00:38 UTC, KKQ-KKQ commented on src/sfizz/FilePool.cpp
> +            fileData.status.compare_exchange_strong(status, FileData::Status::Preloaded);
In this process, the status should not be overwritten if the status is changed at the moment.

2024-02-16 00:38 UTC, KKQ-KKQ commented on src/sfizz/FilePool.cpp
> +            // Initially set status
I added comments on every status change.

2024-02-16 02:19 UTC, KKQ-KKQ commented
I think the processes become more safe.

2024-02-16 05:40 UTC, paulfd commented on src/sfizz/FilePool.cpp
> +        switch(status) {
Thanks!

2024-02-16 14:52 UTC, paulfd commented
Looks good, I'll try to stress test it a bit today or tomorrow thanks!

2024-03-20 07:51 UTC, paulfd commented
@KKQ-KKQ I'm sorry I've been way too swamped at work. I'm merging this without extensive testing so you can proceed. I'll test out things as they come when I can...

すみません ! 🙇

2024-03-20 07:51 UTC, merged

2024-03-20 11:40 UTC, KKQ-KKQ commented
> @KKQ-KKQ I'm sorry I've been way too swamped at work. I'm merging this without extensive testing so you can proceed. I'll test out things as they come when I can...
> 
> すみません ! 🙇

No problem! Thank you!